spring.application.name=springboot
server.port=8071
# 此为遗留项，主程序没有任何代码依赖它
#file.upload-path=${UPLOAD_PATH}

aliyun.oss.endpoint=https://oss-cn-shenzhen.aliyuncs.com
aliyun.oss.access-key-id=${OSS_ACCESS_KEY_ID}
aliyun.oss.access-key-secret=${OSS_ACCESS_KEY_SECRET}
aliyun.oss.bucket-name=liuzimu1
aliyun.oss.region=cn-shenzhen

agent.base-url=http://127.0.0.1:8000/
agent.timeout=5000
agent.read-timeout=60000

jwt.secret=${JWT_KEY}